adding copyrights and small update to doc
temporalio/background-checks pull request #18
Opened 2022-01-16 02:43 UTC by tsurdilo

just adding copyrights and small doc update

2022-01-17 09:29 UTC, robholland commented
I don't think we need the license in every file. Is there some strong reason for doing this?

2022-01-17 09:33 UTC, robholland requested changes

2022-01-17 09:33 UTC, robholland commented on docs/how-to-use.md
> +docker kill $(docker ps -q)
```suggestion
docker compose stop
```

`docker kill $(docker ps -q)` stops all of the docker containers on the system, regardless of they are related to the background-checks application.

2022-01-17 09:33 UTC, robholland commented on docs/how-to-use.md
> +docker rm $(docker ps -a -q)
```suggestion
docker compose rm
```

2022-01-17 09:33 UTC, robholland commented on docs/how-to-use.md
> +docker rmi $(docker images -q)
Not sure why this is needed?

2022-01-17 22:16 UTC, tsurdilo commented
@robholland if you think we don't need to license header thats fine..we have them in all our samples at least for java ones so thought we could add. feel free to disregard

2022-01-18 03:20 UTC, tsurdilo commented
resolved comments

2022-01-18 12:00 UTC, robholland commented
samples-go doesn't have the top of file licences, so lets stick without them.

2022-01-19 03:55 UTC, tsurdilo commented
to be honest i rather add them to the go samples than not add them here cause samples don't have it :) 
to me at least for OSS license headers are important

2022-01-25 09:56 UTC, robholland commented
As discussed on Slack, please remove the per file license headings.

2022-01-25 18:19 UTC, tsurdilo commented
will close this one and redo it as we talked about

2022-01-25 18:19 UTC, closed without merging